meta:
  run_name: Mask R-CNN Baseline
  csv_file: train.csv
  bucket_name: brain-tumor-mlflow
  DEBUG: True

base:
  seed: 719
  fold_num: 2
  epochs: 1
  optuna: false
  train_bs: 2
  valid_bs: 2
  num_workers: 0
  accum_iter: 2
  verbose_step: 5
  trn_schd_batch_update: true
  val_schd_loss_update: false

  mask_threshold: 0.5

dataset:
  name: CellDataset

model:
  name: maskrcnn
  model_arch: resnet50
  pretrained: true

optimizer:
  name: SGD
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  name: StepLR
  step_size: 5
  gamma: 0.1

criterion:
  comment: use Mask R-CNN loss